all: simulador executar remover

simulador:
	gcc -g sim.c Estruturas/FuncTexto.c Estruturas/Interface.c Estruturas/Memorias.c Estruturas/Registradores.c Estruturas/Rotulos.c -o sim

executar:
	./sim

remover:
	rm sim
